spring.application.name=ford

server.port=8085

spring.datasource.url=jdbc:h2:mem:forddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration